### ISSUE TITLE
Add link to this repository

### ISSUE THREAD

**Issue by waldyrious** [addshore/wikicrowd#10]
I was trying to navigate to this repository to leave some feedback/suggestions, and didn't find a link to it on the website.

For example, in the footer where it says "Developed by Addshore", there's a link to Twitter, but I think it would be more appropriate for the link to be to this repository, either replacing the Twitter one, or added alongside it.

**Comment by addshore** [comment]
+1 I'll do this!

**Comment by waldyrious** [comment]
@addshore Could you also add a link back to the [website](https://wikicrowd.toolforge.org) from the repository? There are a "website" and a "repository" fields in the repository home that can be filled. The same text from the website could be used in the description field:

>  Quick and easy micro contributions to the wiki space.

(Maybe it should be included in the main README as well.)

**Comment by addshore** [comment]
Yes!
Could you file this as another issue, else I will 100% forget by time I am next at my laptop! :)
