### ISSUE TITLE
Add link to the website from the repository

### ISSUE THREAD

**Issue by waldyrious** [addshore/wikicrowd#15]
Please add a link back to the [website](https://wikicrowd.toolforge.org/) from the repository. There are a "website" and a "repository" fields in the repository home that can be filled. The same text from the website could be used in the description field:

> Quick and easy micro contributions to the wiki space.

(Maybe it should be included in the main README as well.)

<sub>_Note for future reference: this was originally submitted as a [comment](https://github.com/addshore/wikicrowd/issues/10#issuecomment-1041242139) in #10._</sub>

**Comment by addshore** [comment]
Fixed in the PR!
Also now dont in the website field of the github meta data

**Comment by waldyrious** [comment]
> Also now dont

You mean "done", right? :smile:

**Comment by addshore** [comment]
Yes, Done! :D
