### ISSUE TITLE
About page gives error

### ISSUE THREAD

**Issue by addshore** [addshore/wikicrowd#35]
<img width="257" alt="image" src="https://user-images.githubusercontent.com/3308769/161158598-5be8cd1b-5517-47f0-b3cb-fcdcecf86bd7.png">

This is probably due to the slightly expensive to calculate graphs

MAybe we should just get rid of the graphs!

**Comment by PiotrGackowski** [comment]
For last couple days this page is not working for me at all. Maybe instead of graphs just show raw numbers for last day/last 7 days?
