### ISSUE TITLE
Aliases - please add pl.wiki

### ISSUE THREAD

**Issue by PiotrGackowski** [addshore/wikicrowd#36]
I am ready to check aliases from pl.wiki. I am ready to inform Polish community about them.

**Comment by addshore** [comment]
Now documented in https://github.com/addshore/wikicrowd/blob/main/toolforge/README.md

And the first questions are now there 
<img width="476" alt="image" src="https://user-images.githubusercontent.com/3308769/161374437-e5464d4c-2505-4325-b5d1-f4e1a6a8217e.png">
