### ISSUE TITLE
Find the category to ignore election diagrams in "pie charts"

### ISSUE THREAD

**Issue by addshore** [addshore/wikicrowd#51]
Files like this keep showing up
 - https://commons.wikimedia.org/wiki/File:Macau-legco.svg
 - https://commons.wikimedia.org/wiki/File:Senado_de_Chile_elecci%C3%B3n_1965.svg
 - https://commons.wikimedia.org/wiki/File:Convenci%C3%B3n_Constitucional_2021_(por_alianzas).svg
 
 And I would love to find the right category to ignore to get rid of them!!!!!

**Comment by PiotrGackowski** [comment]
I remember that I marked only 2-3 images as "yes" in whole 250 images block. Thats why I stopped marking this tag.

Second problem in my opinion is with "coveraged brige". Same situation - number of negative markings is too high.

**Comment by PiotrGackowski** [comment]
Category:Pie charts -> Category:Donut charts -> Category:Election apportionment diagrams
