### ISSUE TITLE
Remove Category:Orthophotos by Julio Ruiz de Alda from Seaplanes

### ISSUE THREAD

**Issue by PiotrGackowski** [addshore/wikicrowd#52]
category tree:
Category:Orthophotos by Julio Ruiz de Alda
Category:Julio Ruiz de Alda
Category:Plus Ultra (aircraft)
Category:Dornier Do J Wal
Category:Flying boats of Germany
Category:Flying boats by country
Category:Seaplanes by country
Category:Seaplanes

its 1,5k images.

**Comment by PiotrGackowski** [comment]
@addshore - I am still able to see this orthophotos in seaplane. Its just matter of queue? Because its like 500 photos that I need to mark as "no" and that will be quite annoying

**Comment by addshore** [comment]
Yes, the existing 500 or so will need to empty out before they stop being added.

I did have a way to purge unanswered questions, but the tool forge DBs were struggling yesterday so I couldn't do it!

**Comment by PiotrGackowski** [comment]
OK, I put effort and cleared queue.
