### ISSUE TITLE
Provide keyboard shortcuts

### ISSUE THREAD

**Issue by yasharjit** [addshore/wikicrowd#58]
It would be nice if we are able to use keyboard shortcuts like 1 for yes, 2 for no and 3 for skip or any other keybinding for that matter.

**Comment by yasharjit** [comment]
I was looking through the code and found that you have already set accesskey attribute on button elements. 
So if anyone wants to use the shortcuts you would have to use a combination of keys written in this article for accessing keyboard shortcuts (y for yes, n for no, s for skip) - [https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/accesskey](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/accesskey).

**Comment by PiotrGackowski** [comment]
Problem is that if I want to mark 500 images, using 1-2-3 is much much better for me than y-n-s. Please hold your left hand on 1-2-3 for 15 minutes, and then try to hold this hand on y-n-s for next 15 minutes. Right hand is needed for scrolling etc.

**Comment by waldyrious** [comment]
> I was looking through the code and found that you have already set accesskey attribute on button elements.

This suggests that the shortcuts should probably be mentioned explicitly in the page. I also was unaware of them.
